# Generated by Django 5.1.1 on 2024-09-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-is_done', 'datetime']},
        ),
    ]
